export default [
  {
    title: 'Dashboard',
        route: 'dashboard',
        resource: 'Dashboard',
        action: 'read',
    icon: 'HomeIcon',
    tagVariant: 'light-warning',
  },
  {
    title: 'Smart money tracker',
        route: '',
        resource: 'Dashboard',
        action: 'read',
    icon: 'BriefcaseIcon',
    tagVariant: 'light-warning',
  },
  {
    title: 'Profit calculator',
        route: 'profit-calc',
        resource: 'Calculator',
        action: 'read',
    icon: 'PlusSquareIcon',
    tagVariant: 'light-warning',
  },
  {
    title: 'Alerts',
        route: '',
        resource: 'Dashboard',
        action: 'read',
    icon: 'BellIcon',
    tagVariant: 'light-warning',
  },
  {
    title: 'Settings',
        route: '',
        resource: 'Dashboard',
        action: 'read',
    icon: 'SettingsIcon',
    tagVariant: 'light-warning',
  },
]
